default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: knowledge_vault_development

test:
  <<: *default
  database: knowledge_vault_test

production:
  <<: *default
  database: <%= ENV["KNOWLEDGE_VAULT_DATABASE_NAME"] %>
  username: <%= ENV["KNOWLEDGE_VAULT_DATABASE_USERNAME"] %>
  password: <%= ENV["KNOWLEDGE_VAULT_DATABASE_PASSWORD"] %>
  host: <%= ENV["KNOWLEDGE_VAULT_DATABASE_HOST"]%>
  port: 5432
